/**
 * One-shot / idempotent devnet bring-up for staking_vault.
 *
 * Run manually, after a manual `anchor build && anchor deploy --provider.cluster devnet`:
 *
 *   yarn setup:devnet
 *   yarn setup:devnet --mint-to <PUBKEY> <AMOUNT>
 *
 * Default flow (no flags): creates a stake mint ("TEST", 9 decimals) and a reward mint ("RWD",
 * 9 decimals, wallet as authority) if docs/DEPLOYMENT.md doesn't already record ones, mints
 * 1_000_000 TEST to the wallet the first time the stake mint is created, calls initialize_pool
 * with reward_rate = 1_000_000_000 if the pool doesn't already exist on-chain, and (re)writes
 * docs/DEPLOYMENT.md plus the README's status line with the resulting addresses.
 *
 * `--mint-to <PUBKEY> <AMOUNT>` is a separate, standalone action: mint <AMOUNT> TEST (human
 * units, scaled by the stake mint's decimals) to <PUBKEY>'s associated token account, using the
 * stake mint already recorded in docs/DEPLOYMENT.md. Used later to fund e.g. an agent wallet
 * without re-running the whole setup. Nothing else runs when this flag is passed.
 *
 * Every step logs what it did or why it was skipped, so reruns are safe and legible.
 */
import * as fs from "fs";
import * as path from "path";
import * as os from "os";
import * as anchor from "@coral-xyz/anchor";
import { AnchorProvider, BN, Program, Wallet } from "@coral-xyz/anchor";
import { Connection, Keypair, PublicKey, clusterApiUrl } from "@solana/web3.js";
import {
  createMint,
  getAssociatedTokenAddressSync,
  getOrCreateAssociatedTokenAccount,
  mintTo,
} from "@solana/spl-token";
import type { StakingVault } from "../target/types/staking_vault";

// eslint-disable-next-line @typescript-eslint/no-var-requires
const IDL = require("../target/idl/staking_vault.json");

const CLUSTER_LABEL = "devnet";
const SOLANA_FM_CLUSTER = "devnet-solana";
const RPC_URL = process.env.SETUP_DEVNET_RPC_URL ?? clusterApiUrl("devnet");

const STAKE_MINT_DECIMALS = 9;
const REWARD_MINT_DECIMALS = 9;
const INITIAL_STAKE_MINT_AMOUNT = 1_000_000; // human units
const REWARD_RATE = 1_000_000_000;

const DEPLOYMENT_DOC_PATH = path.resolve(__dirname, "..", "docs", "DEPLOYMENT.md");
const README_PATH = path.resolve(__dirname, "..", "README.md");

function log(step: string, message: string): void {
  console.log(`[setup-devnet] ${step}: ${message}`);
}

function solanaFmAddressLink(address: PublicKey | string): string {
  return `https://solana.fm/address/${address.toString()}?cluster=${SOLANA_FM_CLUSTER}`;
}

function loadWalletKeypair(): Keypair {
  const walletPath = (process.env.ANCHOR_WALLET ?? path.join(os.homedir(), ".config", "solana", "id.json")).replace(
    /^~/,
    os.homedir(),
  );
  const secret = JSON.parse(fs.readFileSync(walletPath, "utf-8"));
  return Keypair.fromSecretKey(Uint8Array.from(secret));
}

interface DeploymentRecord {
  stakeMint?: PublicKey;
  rewardMint?: PublicKey;
}

/** Best-effort parse of a previously-written docs/DEPLOYMENT.md, so reruns don't recreate mints. */
function readExistingDeploymentRecord(): DeploymentRecord {
  if (!fs.existsSync(DEPLOYMENT_DOC_PATH)) {
    return {};
  }
  const contents = fs.readFileSync(DEPLOYMENT_DOC_PATH, "utf-8");
  const base58 = "[1-9A-HJ-NP-Za-km-z]{32,44}";
  const stakeMatch = contents.match(new RegExp(`Stake mint[^|]*\\|\\s*\\[\`(${base58})\``));
  const rewardMatch = contents.match(new RegExp(`Reward mint[^|]*\\|\\s*\\[\`(${base58})\``));
  return {
    stakeMint: stakeMatch ? new PublicKey(stakeMatch[1]) : undefined,
    rewardMint: rewardMatch ? new PublicKey(rewardMatch[1]) : undefined,
  };
}

/** Best-effort deploy-tx lookup: oldest signature found against the program's own address. */
async function findDeployTxSignature(connection: Connection, programId: PublicKey): Promise<string> {
  try {
    const signatures = await connection.getSignaturesForAddress(programId, { limit: 1000 }, "confirmed");
    if (signatures.length === 0) return "unknown (no signatures found for the program address yet)";
    // getSignaturesForAddress returns newest-first; the oldest entry is the best approximation
    // of the initial deploy transaction available without walking the BPF upgradeable loader's
    // separate ProgramData account history.
    return signatures[signatures.length - 1].signature;
  } catch (err) {
    return `unknown (lookup failed: ${String((err as Error)?.message ?? err)})`;
  }
}

function writeDeploymentDoc(fields: {
  programId: PublicKey;
  deployTx: string;
  stakeMint: PublicKey;
  rewardMint: PublicKey;
  pool: PublicKey;
  vault: PublicKey;
}): void {
  const date = new Date().toISOString();
  const doc = `# Devnet Deployment Record

This file is generated by \`scripts/setup-devnet.ts\` — rerunning the script overwrites the table
below with the current on-chain addresses. Do not hand-edit the table; the script also parses it
back out on the next run to decide what already exists and skip recreating it.

**Cluster:** ${CLUSTER_LABEL}
**Last updated:** ${date}

| Field | Value |
|---|---|
| Program ID | [\`${fields.programId.toBase58()}\`](${solanaFmAddressLink(fields.programId)}) |
| Deploy tx | \`${fields.deployTx}\` |
| Stake mint (TEST, ${STAKE_MINT_DECIMALS} decimals) | [\`${fields.stakeMint.toBase58()}\`](${solanaFmAddressLink(fields.stakeMint)}) |
| Reward mint (RWD, ${REWARD_MINT_DECIMALS} decimals) | [\`${fields.rewardMint.toBase58()}\`](${solanaFmAddressLink(fields.rewardMint)}) |
| Pool PDA | [\`${fields.pool.toBase58()}\`](${solanaFmAddressLink(fields.pool)}) |
| Vault ATA | [\`${fields.vault.toBase58()}\`](${solanaFmAddressLink(fields.vault)}) |
`;
  fs.writeFileSync(DEPLOYMENT_DOC_PATH, doc);
  log("docs", `wrote ${path.relative(process.cwd(), DEPLOYMENT_DOC_PATH)}`);
}

/** Replaces the README's devnet status line in place, preserving everything else. */
function updateReadmeStatusLine(programId: PublicKey): void {
  if (!fs.existsSync(README_PATH)) {
    log("readme", "README.md not found, skipping status line update");
    return;
  }
  const readme = fs.readFileSync(README_PATH, "utf-8");
  const liveLine = `**Live on devnet:** [\`${programId.toBase58()}\`](${solanaFmAddressLink(programId)})`;

  const pendingPattern = /^_Devnet: .*$/m;
  const livePattern = /^\*\*Live on devnet:\*\* .*$/m;

  let updated: string;
  if (livePattern.test(readme)) {
    updated = readme.replace(livePattern, liveLine);
  } else if (pendingPattern.test(readme)) {
    updated = readme.replace(pendingPattern, liveLine);
  } else {
    updated = readme.replace(/^## Status\n/m, `## Status\n\n${liveLine}\n`);
  }

  fs.writeFileSync(README_PATH, updated);
  log("readme", "updated devnet status line");
}

async function ensureStakeMint(
  connection: Connection,
  wallet: Keypair,
  existing: PublicKey | undefined,
): Promise<{ mint: PublicKey; freshlyCreated: boolean }> {
  if (existing) {
    log("stake-mint", `already recorded in docs/DEPLOYMENT.md (${existing.toBase58()}), skipping creation`);
    return { mint: existing, freshlyCreated: false };
  }
  const mint = await createMint(connection, wallet, wallet.publicKey, null, STAKE_MINT_DECIMALS);
  log("stake-mint", `created TEST mint ${mint.toBase58()} (${STAKE_MINT_DECIMALS} decimals)`);
  return { mint, freshlyCreated: true };
}

async function ensureRewardMint(
  connection: Connection,
  wallet: Keypair,
  existing: PublicKey | undefined,
): Promise<PublicKey> {
  if (existing) {
    log("reward-mint", `already recorded in docs/DEPLOYMENT.md (${existing.toBase58()}), skipping creation`);
    return existing;
  }
  const mint = await createMint(connection, wallet, wallet.publicKey, null, REWARD_MINT_DECIMALS);
  log("reward-mint", `created RWD mint ${mint.toBase58()} (${REWARD_MINT_DECIMALS} decimals, wallet is authority)`);
  return mint;
}

async function mintTestToWallet(connection: Connection, wallet: Keypair, stakeMint: PublicKey): Promise<void> {
  const ata = await getOrCreateAssociatedTokenAccount(connection, wallet, stakeMint, wallet.publicKey);
  const amount = BigInt(INITIAL_STAKE_MINT_AMOUNT) * 10n ** BigInt(STAKE_MINT_DECIMALS);
  await mintTo(connection, wallet, stakeMint, ata.address, wallet, amount);
  log("mint-to-wallet", `minted ${INITIAL_STAKE_MINT_AMOUNT} TEST to wallet ATA ${ata.address.toBase58()}`);
}

async function ensurePoolInitialized(
  connection: Connection,
  program: Program<StakingVault>,
  wallet: Keypair,
  stakeMint: PublicKey,
  rewardMint: PublicKey,
): Promise<{ pool: PublicKey; vault: PublicKey }> {
  const [pool] = PublicKey.findProgramAddressSync(
    [Buffer.from("pool"), stakeMint.toBuffer()],
    program.programId,
  );
  const vault = getAssociatedTokenAddressSync(stakeMint, pool, true);

  const poolAccountInfo = await connection.getAccountInfo(pool);
  if (poolAccountInfo) {
    log("initialize-pool", `pool ${pool.toBase58()} already exists on-chain, skipping`);
    return { pool, vault };
  }

  await program.methods
    .initializePool(new BN(REWARD_RATE))
    .accountsStrict({
      admin: wallet.publicKey,
      pool,
      stakeMint,
      rewardMint,
      vault,
      tokenProgram: anchor.utils.token.TOKEN_PROGRAM_ID,
      associatedTokenProgram: anchor.utils.token.ASSOCIATED_PROGRAM_ID,
      systemProgram: anchor.web3.SystemProgram.programId,
    })
    .signers([wallet])
    .rpc();
  log(
    "initialize-pool",
    `initialized pool ${pool.toBase58()} (vault ${vault.toBase58()}, reward_rate=${REWARD_RATE})`,
  );
  return { pool, vault };
}

async function runMintToFlag(
  connection: Connection,
  wallet: Keypair,
  destination: PublicKey,
  humanAmount: number,
): Promise<void> {
  const record = readExistingDeploymentRecord();
  if (!record.stakeMint) {
    throw new Error(
      "no stake mint recorded in docs/DEPLOYMENT.md yet — run `yarn setup:devnet` (no flags) first",
    );
  }
  const ata = await getOrCreateAssociatedTokenAccount(connection, wallet, record.stakeMint, destination, true);
  const amount = BigInt(humanAmount) * 10n ** BigInt(STAKE_MINT_DECIMALS);
  await mintTo(connection, wallet, record.stakeMint, ata.address, wallet, amount);
  log(
    "mint-to",
    `minted ${humanAmount} TEST (mint ${record.stakeMint.toBase58()}) to ${destination.toBase58()}'s ATA ${ata.address.toBase58()}`,
  );
}

function parseMintToArgs(argv: string[]): { destination: PublicKey; amount: number } | undefined {
  const flagIndex = argv.indexOf("--mint-to");
  if (flagIndex === -1) return undefined;
  const pubkeyArg = argv[flagIndex + 1];
  const amountArg = argv[flagIndex + 2];
  if (!pubkeyArg || !amountArg) {
    throw new Error("--mint-to requires two arguments: <PUBKEY> <AMOUNT>");
  }
  const destination = new PublicKey(pubkeyArg);
  const amount = Number(amountArg);
  if (!Number.isFinite(amount) || amount <= 0) {
    throw new Error(`--mint-to amount must be a positive number, got "${amountArg}"`);
  }
  return { destination, amount };
}

async function main() {
  const connection = new Connection(RPC_URL, "confirmed");
  const wallet = loadWalletKeypair();
  log("wallet", `${wallet.publicKey.toBase58()} on ${RPC_URL}`);

  const anchorWallet = new Wallet(wallet);
  const provider = new AnchorProvider(connection, anchorWallet, { commitment: "confirmed" });
  anchor.setProvider(provider);
  const program = new Program(IDL, provider) as Program<StakingVault>;

  const mintToArgs = parseMintToArgs(process.argv.slice(2));
  if (mintToArgs) {
    await runMintToFlag(connection, wallet, mintToArgs.destination, mintToArgs.amount);
    return;
  }

  const existing = readExistingDeploymentRecord();

  const { mint: stakeMint, freshlyCreated: stakeMintIsFresh } = await ensureStakeMint(
    connection,
    wallet,
    existing.stakeMint,
  );
  const rewardMint = await ensureRewardMint(connection, wallet, existing.rewardMint);

  if (stakeMintIsFresh) {
    await mintTestToWallet(connection, wallet, stakeMint);
  } else {
    log("mint-to-wallet", "stake mint was reused (not freshly created), skipping initial mint to avoid re-inflating supply");
  }

  const { pool, vault } = await ensurePoolInitialized(connection, program, wallet, stakeMint, rewardMint);

  const deployTx = await findDeployTxSignature(connection, program.programId);

  writeDeploymentDoc({
    programId: program.programId,
    deployTx,
    stakeMint,
    rewardMint,
    pool,
    vault,
  });
  updateReadmeStatusLine(program.programId);

  log("done", "devnet setup complete");
}

main().catch((err) => {
  console.error("[setup-devnet] failed:", err);
  process.exit(1);
});
